version: '3.8'

networks:
  diag_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24

services:
  diag_workstation:
    image: alpine:latest
    container_name: lab_diag_workstation
    hostname: diag-box
    networks:
      diag_net:
        ipv4_address: 172.30.1.10
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: >
      sh -c "apk update && apk add --no-cache \
             curl wget bind-tools nmap tcpdump jq bash \
             busybox-extras iproute2 net-tools iperf3 socat python3 py3-pip && \
             tail -f /dev/null"
    restart: unless-stopped
