version: '3.8'

networks:
  vuln_web_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24

services:
  juice_shop:
    image: bkimminich/juice-shop:latest
    container_name: lab_juice_shop
    networks:
      vuln_web_net:
        ipv4_address: 172.30.2.10
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  mariadb_db:
    image: mariadb:10.5
    container_name: lab_mariadb
    networks:
      vuln_web_net:
        ipv4_address: 172.30.2.30
    environment:
      - MYSQL_ROOT_PASSWORD=LabSecRootPassword2026!
      - MYSQL_DATABASE=dvwa_db
      - MYSQL_USER=dvwa_user
      - MYSQL_PASSWORD=LabSecUserPassword2026!
    restart: unless-stopped

  dvwa_app:
    image: vulnerables/web-dvwa:latest
    container_name: lab_dvwa
    networks:
      vuln_web_net:
        ipv4_address: 172.30.2.20
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - mariadb_db
    restart: unless-stopped
