version: '3.8'

networks:
  cloud_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.5.0/24

services:
  localstack:
    image: localstack/localstack:latest
    container_name: lab_localstack
    networks:
      cloud_net:
        ipv4_address: 172.30.5.10
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=s3,iam,sts,lambda,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  minio_s3:
    image: minio/minio:latest
    container_name: lab_minio_s3
    networks:
      cloud_net:
        ipv4_address: 172.30.5.20
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      - MINIO_ROOT_USER=LabCloudAdmin
      - MINIO_ROOT_PASSWORD=LabCloudSecretKey2026!
    command: server /data --console-address ":9001"
    restart: unless-stopped
